# Docker Compose file for TurtleBot3
#
# Usage:
#
# To build the images:
#   docker compose build
#
# To start up a test-case:
#   docker compose up -d talker listener
#
# To open an interactive shell to a running container:
#   docker exec -it <container_name> bash

services:

  # Husarnet-enabled edge server image
  edge-server-husarnet:
    image: nilsjor/ros-humble-turtlebot:edge-server-husarnet-v2.4
    build:
      context: .
      dockerfile: Dockerfile
      target: server-husarnet-overlay
      args:
        - ROS_WS_PATH=/root/ros2_ws
        - HOSTNAME=edge-server  # Determines which SSH keys to use
    env_file:
      - secret.env  # Used to connect to Husarnet

  # Server image without Husarnet
  server:
    container_name: ros-humble-dev
    image: nilsjor/ros-humble-turtlebot:server-latest
    build:
      context: .
      dockerfile: Dockerfile
      target: server-overlay
      args:
        - ROS_WS_PATH=/root/ros2_ws
    # Interactive shell
    working_dir: /root/ros2_ws
    command: "sleep infinity & wait"
    hostname: damek-edge-docker
    # Networking and inter-process communication
    network_mode: host
    ipc: host
    # Add device and network capabilites
    privileged: true
    # Mount workspace 
    volumes:
      - ~/husarnet-dds:/var/lib/husarnet
      - ~/ros2_ws:/root/ros2_ws
    # Run indefinitely
    restart: unless-stopped

  # Development image without Husarnet
  device:
    container_name: ros-humble-dev
    image: nilsjor/ros-humble-turtlebot:device-latest
    build:
      context: .
      dockerfile: Dockerfile
      # platforms: 
      # - linux/arm64
      # - linux/amd64
      target: device-overlay
      args:
        - ROS_WS_PATH=/root/ros2_ws
    # Interactive shell
    working_dir: /root/ros2_ws
    command: "sleep infinity & wait"
    hostname: turtlebot-docker
    # Networking and inter-process communication
    network_mode: host
    ipc: host
    # Add device and network capabilites
    privileged: true
    # Mount workspace 
    volumes:
      - ~/husarnet-dds:/var/lib/husarnet
      - ~/ros2_ws:/root/ros2_ws
      - ~/ros2_bags:/root/recordings
    # Run indefinitely
    restart: unless-stopped
