# Docker Compose file for TurtleBot3
#
# Usage:
#
# To build the images:
#   docker compose build
#
# To start up a test-case:
#   docker compose up -d talker listener
#
# To open an interactive shell to a running container:
#   docker exec -it <container_name> bash

services:

  # Husarnet-enabled edge server image
  edge-server-husarnet:
    image: nilsjor/ros-humble-turtlebot:edge-server-husarnet-v2.4
    build:
      context: .
      dockerfile: Dockerfile
      target: server-overlay
      args:
        - HOSTNAME=edge-server
    env_file:
      - secret.env
    privileged: true
    network_mode: host
    cap_add:
      - NET_ADMIN

  # Development image without Husarnet
  dev:
    container_name: ros-humble-dev
    image: nilsjor/ros-humble-turtlebot:dev-latest
    build:
      context: .
      dockerfile: Dockerfile
      # platforms: 
      # - linux/arm64
      # - linux/amd64
      target: colcon-overlay
      args:
        - HOSTNAME=turtlebot
        - ROS_WS_PATH=/root/ros2_ws
    # Interactive shell
    stdin_open: true
    tty: true
    working_dir: /root
    command: "sleep infinity & wait"
    hostname: turtlebot-docker
    # Networking and inter-process communication
    network_mode: host
    ipc: host
    # Add device and network capabilites
    privileged: true
    # Mount workspace 
    volumes:
      - ~/husarnet-dds:/var/lib/husarnet
      - ~/ros2_ws:/root/ros2_ws
    # Run indefinitely
    restart: unless-stopped
