# Docker Compose file for TurtleBot3 Examples
#
# Usage:
#
# To build the images:
#   docker compose build
#
# To start up a specific service by name:
#   docker compose up <service_name>
#
# To open an interactive shell to a running container:
#   docker exec -it <container_name> bash

services:

  # Base image
  base:
    image: nilsjor/ros-humble-turtlebot:base
    build:
      context: .
      dockerfile: Dockerfile
      args:
        ROS_DISTRO: humble
      target: base
    # Interactive shell
    stdin_open: true
    tty: true

  # Overlay image with network diagnostics tools
  ip-overlay:
    extends: base
    image: nilsjor/ros-humble-turtlebot:netdiag
    build:
      context: .
      dockerfile: Dockerfile
      target: ip-overlay

  # Overlay image with SSH client
  ssh-overlay:
    extends: base
    image: nilsjor/ros-humble-turtlebot:sshd
    build:
      context: .
      dockerfile: Dockerfile
      target: ssh-overlay

  # Point "latest" tag to the SSH overlay
  latest:
    extends: base
    image: nilsjor/ros-humble-turtlebot:latest
    build:
      context: .
      dockerfile: Dockerfile
      target: ssh-overlay

  # Run test nodes
  talker:
    extends: ip-overlay
    container_name: talker
    command: "ros2 topic pub /chatter std_msgs/String \"{data: 'Hello World'}\" -r 2"
  listener:
    extends: ip-overlay
    container_name: listener
    command: "ros2 topic echo /chatter"
