# Docker Compose file for TurtleBot3
#
# Usage:
#
# To build the images:
#   docker compose build
#
# To start up a test-case:
#   docker compose up -d talker listener
#
# To open an interactive shell to a running container:
#   docker exec -it <container_name> bash

services:

  # Base image
  base:
    image: nilsjor/ros-humble-turtlebot:base
    build:
      context: .
      dockerfile: Dockerfile
      args:
        ROS_DISTRO: humble
      target: base

  # Overlay image with network diagnostics tools
  ip-overlay:
    extends: base
    image: nilsjor/ros-humble-turtlebot:netdiag
    build:
      context: .
      dockerfile: Dockerfile
      target: ip-overlay

  # Overlay image with SSH client
  ssh-overlay:
    image: nilsjor/ros-humble-turtlebot:sshd-v1.0
    build:
      context: .
      dockerfile: Dockerfile
      target: ssh-overlay

  # Run test nodes
  talker:
    image: nilsjor/ros-humble-turtlebot:netdiag
    container_name: talker
    command: "ros2 topic pub /chatter std_msgs/String \"{data: 'Hello World'}\" -r 2"

  listener:
    image: nilsjor/ros-humble-turtlebot:netdiag
    container_name: listener
    command: "ros2 topic echo /chatter"
