# Docker Compose file for TurtleBot3
#
# Usage:
#
# To build the images:
#   docker compose build
#
# To start up a test-case:
#   docker compose up -d talker listener
#
# To open an interactive shell to a running container:
#   docker exec -it <container_name> bash

services:

  # Base image
  base:
    image: nilsjor/ros-humble-turtlebot:base-v1.1
    build:
      context: .
      dockerfile: Dockerfile
      args:
        ROS_DISTRO: humble
      target: base

  # Overlay image with network diagnostics tools
  ip-overlay:
    image: nilsjor/ros-humble-turtlebot:netdiag-v1.2
    build:
      context: .
      dockerfile: Dockerfile
      target: netdiag-overlay

  # Overlay image with SSH client
  ssh-overlay:
    image: nilsjor/ros-humble-turtlebot:sshd-v1.2
    build:
      context: .
      dockerfile: Dockerfile
      target: ssh-overlay

  # Run test nodes
  talker:
    container_name: talker
    image: nilsjor/ros-humble-turtlebot:talker-v0.3
    build:
      context: .
      dockerfile: Dockerfile
      target: talker
    environment:
      - ROS_DISCOVERY_SERVER=discovery:11811
    depends_on:
      - discovery

  listener:
    container_name: listener
    image: nilsjor/ros-humble-turtlebot:listener-v0.3
    build:
      context: .
      dockerfile: Dockerfile
      target: listener
    environment:
      - ROS_DISCOVERY_SERVER=discovery:11811
    depends_on:
      - discovery

  discovery:
    container_name: discovery
    image: nilsjor/ros-humble-turtlebot:discovery-v0.3
    build:
      context: .
      dockerfile: Dockerfile
      target: discovery-server
