# Docker Compose file for TurtleBot3
#
# Usage:
#
# To build the images:
#   docker compose build
#
# To start up a test-case:
#   docker compose up -d talker listener
#
# To open an interactive shell to a running container:
#   docker exec -it <container_name> bash

services:

  # Base image
  base:
    image: nilsjor/ros-humble-turtlebot:base-v1.3
    build:
      context: .
      dockerfile: Dockerfile
      args:
        ROS_DISTRO: humble
      target: base

  # Overlay image with ros-desktop
  desktop:
    image: nilsjor/ros-humble-turtlebot:desktop-latest
    build:
      context: .
      dockerfile: Dockerfile
      target: desktop

  # Overlay image with network diagnostics tools
  husarnet:
    image: nilsjor/ros-humble-turtlebot:husarnet-v1.2
    build:
      context: .
      dockerfile: Dockerfile
      target: husarnet-overlay
    environment:
      - HUSARNET_HOSTNAME=husarnet-test
    env_file:
      - secret.env
    privileged: true
    cap_add:
      - NET_ADMIN
      

  # # Run test nodes
  # talker:
  #   container_name: talker
  #   image: nilsjor/ros-humble-turtlebot:talker-v0.7
  #   build:
  #     context: .
  #     dockerfile: Dockerfile
  #     target: talker
  #   environment:
  #     - ROS_DISCOVERY_SERVER=discovery:11811
  #   depends_on:
  #     - discovery

  # listener:
  #   container_name: listener
  #   image: nilsjor/ros-humble-turtlebot:listener-v0.7
  #   build:
  #     context: .
  #     dockerfile: Dockerfile
  #     target: listener
  #   environment:
  #     - ROS_DISCOVERY_SERVER=discovery:11811
  #   depends_on:
  #     - discovery

  # discovery:
  #   container_name: discovery
  #   build:
  #     context: .
  #     dockerfile: Dockerfile
  #     target: discovery-server
  #   image: nilsjor/ros-humble-turtlebot:discovery-v0.8
