# Docker Compose file for TurtleBot3
#
# Usage:
#
# To build the images:
#   docker compose build
#
# To start up a test-case:
#   docker compose up -d talker listener
#
# To open an interactive shell to a running container:
#   docker exec -it <container_name> bash

services:

  # Husarnet-enabled edge server image
  husarnet-edge:
    image: nilsjor/ros-humble-turtlebot:edge-server-husarnet-v2.4
    build:
      context: .
      dockerfile: Dockerfile
      target: server-overlay
      args:
        - HOSTNAME=edge-server
    env_file:
      - secret.env
    privileged: true
    network_mode: "host"
    cap_add:
      - NET_ADMIN

  # TurtleBot3 image without intergrated husarnet
  husarnet-device:
    image: nilsjor/ros-humble-turtlebot:build-tools-v2.4
    build:
      context: .
      dockerfile: Dockerfile
      # platforms: 
      # - linux/arm64
      # - linux/amd64
      target: colcon-overlay
      args:
        - HOSTNAME=turtlebot
        - ROS_WS_PATH=/root/ros2_ws
    privileged: true
    network_mode: "host"
    volumes:
      - ~/husarnet-dds:/var/lib/husarnet
      - ~/ros2_ws:/root/ros2_ws
    cap_add:
      - NET_ADMIN
