# Docker Compose file for TurtleBot3
#
# Usage:
#
# To build the images:
#   docker compose build
#
# To start up a test-case:
#   docker compose up -d talker listener
#
# To open an interactive shell to a running container:
#   docker exec -it <container_name> bash

services:

  # Husarnet-enabled edge server image
  husarnet-edge:
    image: nilsjor/ros-humble-turtlebot:edge-server-husarnet-v2.3
    build:
      context: .
      dockerfile: Dockerfile
      target: server-overlay
      args:
        - HOSTNAME=edge-server
    env_file:
      - secret.env
    privileged: true
    network_mode: "host"
    cap_add:
      - NET_ADMIN

  # Husarnet-enabled device node image
  husarnet-device:
    image: nilsjor/ros-humble-turtlebot:device-node-v2.3
    build:
      context: .
      dockerfile: Dockerfile
      # platforms: 
      # - linux/arm64
      # - linux/amd64
      target: build-overlay
      args:
        - HOSTNAME=turtlebot
    env_file:
      - secret.env
    privileged: true
    network_mode: "host"
    volumes:
      - ~/appdata/husarnet-config:/var/lib/husarnet
      - /var/tmp/husarnet-dds:/var/tmp/husarnet-dds
    cap_add:
      - NET_ADMIN
